# Generated by Django 5.1.2 on 2024-11-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_participants'),
        ('users', '0003_customuser_events_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='participants_of', to='events.event'),
        ),
    ]
